### ISSUE TITLE
Duplicate entities

### ISSUE THREAD

**Issue by yolo-bird** [serlo/serlo.org#482] opened 2020-08-18 13:03 UTC
Beside copying and moving entities it would be nice to able to duplicate them, too.

**Comment by kulla** [comment] 2020-08-18 13:05
@yolo-bird Duplicate of #427 ?

**Comment by yolo-bird** [comment] 2020-08-18 13:21
Good catch. I was thinking of duplicating within one language version. So in that sense #427 is even more general.

**Comment by kulla** [comment] 2020-08-18 13:58
Duplicate of #427

**Closed by kulla** 2020-08-18 13:58 UTC
Labels: duplicate, enhancement
