### ISSUE TITLE
merge "subject home" / "all topics"

### ISSUE THREAD

**Issue by simonkoehl** [serlo/serlo.org#266] opened 2019-05-09 13:42 UTC
"subject home" and "all topics" are redundant in subject breadcrums. Additionally both sides show a taxonomy overview

potential problems
- at current state, "all topics" is needed in side navigation to build the subject taxonomy

**Comment by kulla** [comment] 2020-06-15 12:03
Duplicate of https://github.com/serlo/serlo.org/issues/444

**Closed by kulla** 2020-06-15 12:03 UTC
Labels: duplicate
