### ISSUE TITLE
anchor with new edtr.io plugin jumps a little bit too far 

### ISSUE THREAD

**Issue by metzgaria** [serlo/serlo.org#238] opened 2020-01-21 13:14 UTC
example: [Serlo Profile](https://de.serlo.org/user/profile/metzgaria)
(anchor is set before the headings)
(@Knorrke said it's only a serlo issue, was fixed with CSS in old editor)

**Comment by Knorrke** [comment] 2020-01-21 13:23
It does jump to the correct position, but we have the fixed breadcrumbs bar hiding it, so we want to adjust this. We have a fix for this with some `:target` pseudo-element...

**Comment by kulla** [comment] 2020-05-12 17:00
Duplicate of #389

**Closed by kulla** 2020-05-12 17:00 UTC
Labels: bug, edtr-io
