### ISSUE TITLE
Missing error message for course page without title

### ISSUE THREAD

**Issue by metzgaria** [serlo/serlo.org#382] opened 2020-04-19 16:45 UTC
When you want to save a course (page) without a title, it is not possible, but you are asked to inform a developer. An error message could be useful here.

![grafik](https://user-images.githubusercontent.com/26926820/79693935-ca948a80-826d-11ea-9bbc-6c9977d64434.png)

**Comment by inyono** [comment] 2020-04-19 18:04
Duplicate of 360

**Closed by inyono** 2020-04-19 18:04 UTC
